spring:
  application:
    name: menu-service
  datasource:
    url: jdbc:postgresql://172.30.60.1:5432/demoapp_menu
    username: postgres
    password: Nut@n803212
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      enabled: true
      retry:
        initial-interval: 1000
        max-interval: 2000
        max-attempts: 5
        multiplier: 1.1

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# JWT Configuration
app:
  jwt:
    secret: ZGVtb0FwcFNlY3JldEtleTEyMzQ1Njc4OTAxMjM0NTY3ODkw
    expiration: 86400000 